---
- name: General Setup
  become: yes
  become_user: root
  hosts: all
  vars_files:
    - "{{ protected_storage }}/secret_vars.yml"
  roles:
    - common
    - docker
    - smb_mount
    - autofs
    - tersmitten.locales
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1

      # Set the default forward policy of ufw
      ufw_default_forward_policy: ACCEPT

      # Enable IPv6 traffic.
      net.ipv6.conf.all.disable_ipv6: 0

      # Enable IPv6 traffic forwarding.
      net.ipv6.conf.all.forwarding: 1

      # Enable IPv6 autoconf.
      net.ipv6.conf.default.autoconf: 1
