---
- name: General Setup
  become: yes
  become_user: root
  hosts: all
  vars_files:
    - "{{ protected_storage }}/secret_vars.yml"
  roles:
    - common
    - docker
    - smb_mount
    - autofs
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - dev-sec.nginx-hardening
