---
- name: General Setup
  become: yes
  become_user: root
  hosts: all
  # vars:
  #   smb_username: default_user
  #   smb_password: default_password
  #   smb_hostname: default_hostname
  #   mount_points:
  #     -
  #   mount_destination: mnt
  vars_files:
    - "{{ protected_storage }}/secret_vars.yml"
  roles:
    - common
    - docker
    - smb_mount
    - autofs
    - datadog
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - dev-sec.nginx-hardening
