---
- name: General Setup
  become: yes
  become_user: root
  hosts: all
  vars_files:
    - "{{ protected_storage }}/secret_vars.yml"
  roles:
    - common
    - docker
    - smb_mount
    - autofs
    - os-hardening
    - tersmitten.locales
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
