#!/usr/bin/env bash
set -e

cd "$(dirname "$0")" || exit

echo "Cloning secrets repo"
git clone "git@github.com:faun/seedling-vault.git" ../protected 2>/dev/null || \
  (cd ../protected && git pull >/dev/null)

echo "Initializing ansible vault"
./configure_vault_password

echo "Done!"
