#!/bin/bash
set -e
# From https://jefframnani.com/use-ansible-vault-with-macos-keychain/

# Keychain query fields.
# LABEL is the value you put for "Keychain Item Name" in Keychain.app.
LABEL="ansible-vault-password"
ACCOUNT_NAME="faun"

get_password() {
  /usr/bin/security find-generic-password \
    -w \
    -a "$ACCOUNT_NAME" \
    -l "$LABEL"
}

password_exists() {
  if get_password > /dev/null 2>&1
  then
    return 0
  else
    return 1
  fi
}

store_password() {
  /usr/bin/security \
    -i \
    add-generic-password \
    -a "$ACCOUNT_NAME" \
    -s "$LABEL" \
    -w
}

request_and_store() {
  echo "Please enter your $LABEL:"
  store_password
  return 0
}

(password_exists && echo "Found password") || request_and_store
