#!/bin/bash
# From https://jefframnani.com/use-ansible-vault-with-macos-keychain/

# Keychain query fields.
# LABEL is the value you put for "Keychain Item Name" in Keychain.app.
LABEL="ansible-vault-password"
ACCOUNT_NAME="faun"

/usr/bin/security find-generic-password -w -a "$ACCOUNT_NAME" -l "$LABEL"
