---
- name: Update apt cache and upgrade packages
  tags: ['system', 'apt']
  apt:
    update_cache: 'yes'
    cache_valid_time: 86400
    upgrade: 'no'
    autoremove: 'yes'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install vim
  tags: ['system', 'apt']
  apt:
    name: vim
    state: present
