---
- name: Install ufw
  tags: ['system', 'apt', 'firewall']
  apt: name=ufw

- name: Allow ssh through firewall
  tags: ['system', 'firewall']
  ufw: proto=tcp port=22 rule=allow

- name: Set ufw policy
  tags: ['system', 'firewall']
  ufw: state=enabled direction=incoming policy=deny

- name: Allow nginx firewall
  tags: ['system', 'firewall']
  ufw: proto=tcp port=80 rule=allow

- name: Allow nginx ssl firewall
  tags: ['system', 'firewall']
  ufw: proto=tcp port=443 rule=allow
