---
- name: Register current timezone
  tags: ['system', 'timezone']
  command: cat /etc/timezone
  register: current_timezone
  changed_when: False

- name: Show current value of tz
  tags: ['system', 'timezone']
  debug:
    var: "{{ item }}"
  with_items:
    - ansible_date_time.tz
    - tz
    - current_timezone.stdout
    - timezone
  when: ansible_check_mode

- name: set timezone to America/Pacific
  tags: ['system', 'timezone']
  timezone:
    name: "America/Los_Angeles"

- name: Debug timezone value
  tags: ['system', 'timezone']
  debug:
    var: timezone

- name: Debug current timezone
  tags: ['system', 'timezone']
  debug:
    var: ansible_date_time.tz
