---
- name: Register current timezone
  tags: ['system', 'timezone']
  command: cat /etc/timezone
  register: current_timezone
  changed_when: False

- name: Show current value of tz
  tags: ['system', 'timezone']
  debug: 
    var: "{{ item }}"
  with_items:
    - ansible_date_time.tz
    - tz
    - current_timezone.stdout
    - timezone
  when: debug_mode

- name: Set timezone
  tags: ['system', 'timezone']
  command: timedatectl set-timezone {{ timezone}}
  when: ansible_date_time.tz != tz
  
- name: Link timezone file to /etc/localtime
  tags: ['system', 'timezone']
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
  notify: Update TZdata
  when: ansible_date_time.tz != tz

- name: Set timezone value in /etc/timezone
  tags: ['system', 'timezone']
  file:
    content: "{{ timezone }}\n"
    dest: /etc/timezone
    state: link
    force: yes
  notify: Update TZdata
  register: file_link
  when: current_timezone.stdout != timezone
