---
- set_fact: longsleep=false
- set_fact: longsleep=true
  when: "'longsleep' in ansible_kernel"

- name: Install dependencies
  tags: ['system', 'packages', 'apt', 'docker']
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - apparmor

- name: Add Docker repository key
  tags: ['system', 'packages', 'apt', 'docker']
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

- name: "Add Docker repository and update apt cache for {{ ansible_distribution_release }}"
  tags: ['system', 'packages', 'apt', 'docker']
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: present
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"

- name: Install docker.io using apt
  tags: ['system', 'packages', 'apt', 'docker']
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
    update_cache: yes
  when: longsleep
  with_items:
    - docker.io
  check_mode: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install docker.io using apt
  tags: ['system', 'packages', 'apt', 'docker']
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
    update_cache: yes
  when: longsleep
  with_items:
    - docker.io
  check_mode: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Make sure docker is running
  tags: ['system', 'docker', 'services']
  service:
    name: docker
    state: started
