---

- name: Ensure latest python2.7 is installed
  tags: ['system', 'packages', 'apt', 'docker', 'python']
  apt:
    pkg: python2.7
    state: latest
    install_recommends: no

- name: Remove Legacy Docker Packages
  tags: ['system', 'packages', 'apt', 'docker']
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker-hypriot
    - docker-ce
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install docker dependencies
  tags: ['system', 'packages', 'apt', 'docker']
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: yes
    update_cache: yes
  with_items:
    - apparmor
    - apt-transport-https
    - ca-certificates
    - curl
    - docker-compose
    - gnupg2
    - software-properties-common
  check_mode: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Docker
  tags: ['system', 'packages', 'apt', 'docker']
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: yes
    update_cache: yes
  with_items:
    - docker.io
    - docker-compose
  check_mode: no
  ignore_errors: "{{ ansible_check_mode }}"

- name: Make sure docker is running
  tags: ['system', 'docker', 'services']
  service:
    name: docker
    state: started
